language: bash

env:
  - SHUNIT_COLOR='always'

script:
  - make init
  - make test

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      script:
        - make check
    - os: linux
      dist: trusty
